version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8099:8099"
    environment:
      - PORT=8099
      - MONGO_URI=mongodb://mongo:27017/mydata
      - JWT_SECRET=mysecretkey
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8099
    depends_on:
      - backend

volumes:
  mongo-data:
