version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=myData

  backend:
    build: ./backend
    ports:
      - "8099:8099"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/myData
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://backend:8099/api
    volumes:
      - ./frontend/src:/app/src
volumes:
  mongo-data: